apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asr-api-autoscaler
  namespace: forensic-tools
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asr-api

  minReplicas: 1
  maxReplicas: 2

  metrics:
    - type: Pods
      pods:
        metric:
          name: dcgm_gpu_utilization_percent
        target:
          type: AverageValue
          averageValue: "80"
